/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.academico;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author SCIS2-28
 */
public class VentanaPrincial extends javax.swing.JFrame {
   
    int sizeMenores = 0;
    
    int arrayMenores[];
    int arrayMayores[] = new int[5];
    int arrayAdultosMayores[] = new int[5];
    int im = 0;
    int ima = 0;
    int iam = 0;

    public VentanaPrincial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittle = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        search = new javax.swing.JButton();
        size = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tittle.setText("SISTEMA ACADÉMICO");

        create.setText("Crear");
        create.setEnabled(false);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        search.setText("Consultar");
        search.setEnabled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        size.setText("Tamaños");
        size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(create)
                        .addGap(55, 55, 55)
                        .addComponent(search)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(140, Short.MAX_VALUE)
                        .addComponent(tittle)))
                .addGap(39, 39, 39)
                .addComponent(size)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittle)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(search)
                    .addComponent(size))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed

        int age = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese su edad en números enteros y sin espacios"));
        
        //validar si tiene espacios o no es número
        
        if (age < 18) {
            JOptionPane.showMessageDialog(rootPane, "Usted es menor de edad");
            if (sizeMenores == 5) {
                JOptionPane.showMessageDialog(rootPane, "no hay espacio para almacenar");
            } else {
                arrayMenores[im] = age;
                im++;
            }
        } else if (age >= 18 && age < 65) {
            JOptionPane.showMessageDialog(rootPane, "Usted es mayor de edad");
            if (ima == 5) {
                JOptionPane.showMessageDialog(rootPane, "no hay espacio para almacenar");
            } else {
                arrayMayores[ima] = age;
                ima++;
            }
        } else if (age >= 65) {
            JOptionPane.showMessageDialog(rootPane, "Usted es adulto mayor");
            if (iam == 5) {
                JOptionPane.showMessageDialog(rootPane, "no hay espacio para almacenar");
            } else {
                arrayAdultosMayores[iam] = age;
                iam++;
            }
        }
        search.setEnabled(true);
    }//GEN-LAST:event_createActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        JOptionPane.showMessageDialog(rootPane, "menores almacenados: " + Arrays.toString(arrayMenores) + " \nAdultos almacenados: " + Arrays.toString(arrayMayores) + " \nAdultos mayores almacenados: " + Arrays.toString(arrayAdultosMayores));
    }//GEN-LAST:event_searchActionPerformed

    private void sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeActionPerformed
         sizeMenores = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese el tamaño del arreglo de menores en números enteros y sin espacios"));
         arrayMenores = new int[sizeMenores];
         create.setEnabled(true);
         
    }//GEN-LAST:event_sizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JButton search;
    private javax.swing.JButton size;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
